name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    # ref: https://github.com/marketplace/actions/automated-build-android-app-with-github-action
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Print generated version
      run: ./gradlew --quiet androidGitVersion

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build apk debug project (APK)
      run: ./gradlew packageDebugAndroidTest

    - name: Copy Apks to dist folder
      run: |
        rm -fr dist && mkdir -p dist
        mv app/build/outputs/apk/debug/app-debug.apk dist/app-uiautomator.apk
        mv app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk dist/app-uiautomator-test.apk
    
    - name: Publish APKs
      uses: actions/upload-artifact@v3
      with:
        name: app-uiautomator
        path: dist/
      


